### PR TITLE
Add flag to show output and override ok/crit msg

### PR DESCRIPTION
**Pull request by raags**
- show output is helpful when command failure has actionable output
- ok/critical message is useful for meanigful alerts
- fixed failing checks

### CODE REVIEW

**Comment by mattyjones** [comment]
@raggs I like the idea of this. I would rather see it implemented class wide so all plugins could utilize it. @portertech thoughts?

**Comment by raags** [comment]
@mattyjones we could add these options as always available in sensu-plugins, and overriding the ok/crit message.

**Comment by mattyjones** [comment]
@raags 

Any progress on this?

**Comment by raags** [comment]
@mattyjones I tried to make this work but I'm not sure how to make this available class wide. From what I understand the way mixlib/cli works the options have to be present on the final plugin class. I'm new to ruby; not sure where to hook these 'default' options.

**Comment by sstarcher** [comment]
@raags This was merged back in May for mixlib/cli.  I don't know what version sensu is using.

https://github.com/chef/mixlib-cli/pull/13

**Comment by cwjohnston** [comment]
@sstarcher  @raags v1.3.0 of sensu-plugin shipped yesterday with updated dependency on mixlib-cli >= 1.5.0 (see https://github.com/sensu-plugins/sensu-plugin/commit/aa59019a584eae88f3e784d7079f59a762879418) which may help? This new version of sensu-plugin is not yet shipping with omnibus Sensu but is available via rubygems.

**Comment by majormoses** [comment]
This has not been touched in almost a year, I am gonna close this and feel free to message me or re-open when someone wants to actually do this. Feel free to open an issue to track this request.

**Pull request closed without merging**
