### PR TITLE
check-process: Select matching process to match what --help says

### PR DESCRIPTION
**Pull request by maoe**
## Pull Request Checklist

**Is this in reference to an existing issue?**

No.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets
    - Nothing to change.

- [x] Binstubs are created if needed
    - Nothing to change

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

It's not a new plugin.

- [x] Tests

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Fixing discrepancies between the actual behavior of `-z`, `-r`, `-P` and `-T`, and what the help messages say they do.

#### Known Compatablity Issues

Currently `-z`, `-r`, `-P`, and `-T` **reject** matching processes. So there is no way to check e.g. if there are processes that have more than 100 threads. `-T 100` filters out such processes and reports that there are other processes that didn't match the filter.

This patch fixes the issue by `select!`ing matching processes. For the example above, we should be able to

```
check-process.rb -T 100 --critical-over 1
```

to detect such processes.

### CODE REVIEW

**Comment by maoe** [comment]
https://travis-ci.org/sensu-plugins/sensu-plugins-process-checks/jobs/149661232 failed for some reason. I believe it has nothing to do with my changes.

**Comment by eheydrick** [comment]
You are right, it has to do with the version of the `json` gem being pulled in. That's getting fixed in the next release of `sensu-plugin` which should be out soon.

**Comment by sstarcher** [comment]
@eheydrick are we waiting for the release of sensu-plugin to merge this?

**Comment by eheydrick** [comment]
`sensu-plugin` 1.4.1 is out with pinned json dependency and the build passes now so 👍 to merge.

**Pull request merged**
